### ISSUE TITLE
To set up a default configuration file, symbolic link in /etc/abf/mock/configs have to be created. I need sudo rights to do it.

### ISSUE THREAD

**Issue by tpgxyz** [OpenMandrivaSoftware/abf-console-client#10]
To set up a default configuration file, symbolic link in /etc/abf/mock/configs have to be created. I need sudo rights to do it.

So i execute it with sudo:
```
[tpg@tpg-virtualbox gc]$ sudo abf mock -c cooker-x86_64-main.cfg
[sudo] hasło użytkownika tpg: 
Traceback (most recent call last):
  File "/usr/bin/abf", line 1725, in <module>
    from abf.console.misc import *
  File "/usr/lib/python3.8/site-packages/abf/console/misc.py", line 20, in <module>
    log = Log('models')
  File "/usr/lib/python3.8/site-packages/abf/console/log.py", line 27, in __init__
    logging.config.fileConfig(os.path.expanduser(conf_path))
  File "/usr/lib64/python3.8/logging/config.py", line 71, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib64/python3.8/logging/config.py", line 104, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib64/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'

```

**Comment by fedya** [comment]
probably it's python38

**Comment by fedya** [comment]
is still actual?

**Comment by mikhailnov** [comment]
А я вот вообще не понял, как пользоваться abf mock, он, может, сломан?

**Comment by fedya** [comment]
каждый день работает у меня
