### ISSUE TITLE
После переустановки перестал работать и нет авторизации под пользователем

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaSoftware/abf-console-client#31]
nikolanp@rosa2021 ~> abf get blacksaber/blacksaber_repo -b master
Клонирование в «blacksaber_repo»…
X11 forwarding request failed on channel 0
nikolanp@rosa2021 ~>  cd /home/nikolanp/blacksaber_repo
nikolanp@rosa2021 ~/blacksaber_repo (master)> abf put -m "Add my repo"
Traceback (most recent call last):
  File "/usr/bin/abf", line 1783, in <module>
    command_line.func()
  File "/usr/bin/abf", line 825, in put
    error_count = upload_files(models, min_size, remove_files=not command_line.do_not_remove_files, path=path, upload_all=command_line.upload_all)
  File "/usr/lib/python3.8/site-packages/abf/console/misc.py", line 574, in upload_files
    sha_hash = models.jsn.upload_file(source)
  File "/usr/lib/python3.8/site-packages/abf/api/jsn.py", line 260, in upload_file
    res = self.get_file_info_by_hash(sha_hash)
  File "/usr/lib/python3.8/site-packages/abf/api/jsn.py", line 309, in get_file_info_by_hash
    return self.get_url_contents(URL, GET=GET, file_store=True)
  File "/usr/lib/python3.8/site-packages/abf/api/jsn.py", line 196, in get_url_contents
    cache_etags.put(url, etag_new)
  File "/usr/lib/python3.8/site-packages/beaker/cache.py", line 317, in put
    self._get_value(key, **kw).set_value(value)
  File "/usr/lib/python3.8/site-packages/beaker/container.py", line 409, in set_value
    self.namespace.acquire_write_lock()
  File "/usr/lib/python3.8/site-packages/beaker/container.py", line 220, in acquire_write_lock
    r = self.access_lock.acquire_write_lock(wait)
  File "/usr/lib/python3.8/site-packages/beaker/synchronization.py", line 186, in acquire_write_lock
    x = self.do_acquire_write_lock(wait)
  File "/usr/lib/python3.8/site-packages/beaker/synchronization.py", line 261, in do_acquire_write_lock
    filedescriptor = self._open(os.O_CREAT | os.O_WRONLY)
  File "/usr/lib/python3.8/site-packages/beaker/synchronization.py", line 242, in _open
    filedescriptor = os.open(self.filename, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/abf_cache/etags/7/75/751ebf2d42780d2581ffd420d6a310f866cdcc67.lock'
nikolanp@rosa2021 ~/blacksaber_repo (master) [1]> sudo abf mock
[sudo] пароль для nikolanp: 
Авторизация не удалась. Неверный логин или пароль
nikolanp@rosa2021 ~/blacksaber_repo (master)> 
пароля на пользователе нет.
nikolanp@rosa2021 ~> rpm -qa | grep abf
python3-abf-3.0.3.6-1.noarch
abf-console-client-3.0.3.6-1.noarch
nikolanp@rosa2021 ~
Операционная система: ROSA Fresh Desktop 2021.1
Версия KDE Plasma: 5.22.5
Версия KDE Frameworks: 5.86.0
Версия Qt: 5.15.2
Версия ядра: 5.10.74-generic-2rosa2021.1-x86_64 (64-бита)
Графическая платформа: X11
Процессоры: 6 × AMD FX(tm)-6300 Six-Core Processor
Память: 7,7 ГиБ ОЗУ
Графический процессор: NVC1

**Comment by saber716rus** [comment]
решается командой sudo rm -fvr /tmp/abf*
