### ISSUE TITLE
add a spec build with the mock command

### ISSUE THREAD

**Issue by saber716rus** [OpenMandrivaSoftware/abf-console-client#38]
[nikolanp@rosa2021 RyzenAdj]$ abf mock
Traceback (most recent call last):
  File "/usr/bin/abf", line 1783, in <module>
    command_line.func()
  File "/usr/bin/abf", line 540, in localbuild_mock_urpm
    find_spec_problems()
  File "/usr/lib/python3.8/site-packages/abf/console/misc.py", line 259, in find_spec_problems
    res = get_project_data(spec_path)
  File "/usr/lib/python3.8/site-packages/abf/console/misc.py", line 99, in get_project_data
    rpm_spec = parse_spec_silently(ts, spec_path)
  File "/usr/lib/python3.8/site-packages/abf/console/misc.py", line 70, in parse_spec_silently
    rpm_spec = ts.parseSpec(spec_path)
  File "/usr/lib64/python3.8/site-packages/rpm/transaction.py", line 45, in parseSpec
    return rpm.spec(specfile)
ValueError: can't parse specfile

[nikolanp@rosa2021 RyzenAdj]$

**Comment by fedya** [comment]
Из бага ничего не понятно, что происходит.
Что за проект, ссылка на спек, что именно не может распарсит, собирается ли на абф
